/**
@file: MCAL_INTERNAL_INTERRUPTS.h
@author: M4_TEAM 
@creation_date: date
*/

#ifndef MCAL_INTERNAL_INTERRUPTS_H
#define MCAL_INTERNAL_INTERRUPTS_H

/*******************INCLUDES SECTION START************************/
#include "../REGISTERS_DEFINITIONS/REGISTERS_DEFINITIONS.h"
/*******************INCLUDES SECTION END  ************************/




/*******************MACROS DEFINITION SECTION START***************/

/*******************MACROS DEFINITION SECTION END  ***************/




/*******************MACROS LIKE FUNCTIONS SECTION START***********/
//Timer 1 Interrupts    
#define TIMER1_UPDATE_INTERRUPT_ENABLE()        (SET_BIT_K(TIM1_DIER,TIMX_DIER_UIE))
#define TIMER1_CC1_INTERRUPT_ENABLE()           (SET_BIT_K(TIM1_DIER,TIMX_DIER_CC1IE))
#define TIMER1_CC2_INTERRUPT_ENABLE()           (SET_BIT_K(TIM1_DIER,TIMX_DIER_CC2IE))
#define TIMER1_CC3_INTERRUPT_ENABLE()           (SET_BIT_K(TIM1_DIER,TIMX_DIER_CC3IE))
#define TIMER1_CC4_INTERRUPT_ENABLE()           (SET_BIT_K(TIM1_DIER,TIMX_DIER_CC4IE))

#define TIMER1_UPDATE_INTERRUPT_DISABLE()       (CLEAR_BIT_K(TIM1_DIER,TIMX_DIER_UIE))
#define TIMER1_CC1_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM1_DIER,TIMX_DIER_CC1IE))
#define TIMER1_CC2_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM1_DIER,TIMX_DIER_CC2IE))
#define TIMER1_CC3_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM1_DIER,TIMX_DIER_CC3IE))
#define TIMER1_CC4_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM1_DIER,TIMX_DIER_CC4IE))

#define TIMER1_CLEAR_FLAG()                     (CLEAR_BIT_K(TIM1_SR,TIMX_SR_UIF))
#define TIMER1_CCP1_CLEAR_FLAG()                (CLEAR_BIT_K(TIM1_SR,TIMX_SR_CC1IF))
#define TIMER1_CCP2_CLEAR_FLAG()                (CLEAR_BIT_K(TIM1_SR,TIMX_SR_CC2IF))
#define TIMER1_CCP3_CLEAR_FLAG()                (CLEAR_BIT_K(TIM1_SR,TIMX_SR_CC3IF))
#define TIMER1_CCP4_CLEAR_FLAG()                (CLEAR_BIT_K(TIM1_SR,TIMX_SR_CC4IF))

//Timer 2 Interrupts    
#define TIMER2_UPDATE_INTERRUPT_ENABLE()        (SET_BIT_K(TIM2_DIER,TIMX_DIER_UIE))
#define TIMER2_CC1_INTERRUPT_ENABLE()           (SET_BIT_K(TIM2_DIER,TIMX_DIER_CC1IE))
#define TIMER2_CC2_INTERRUPT_ENABLE()           (SET_BIT_K(TIM2_DIER,TIMX_DIER_CC2IE))
#define TIMER2_CC3_INTERRUPT_ENABLE()           (SET_BIT_K(TIM2_DIER,TIMX_DIER_CC3IE))
#define TIMER2_CC4_INTERRUPT_ENABLE()           (SET_BIT_K(TIM2_DIER,TIMX_DIER_CC4IE))

#define TIMER2_UPDATE_INTERRUPT_DISABLE()       (CLEAR_BIT_K(TIM2_DIER,TIMX_DIER_UIE))
#define TIMER2_CC1_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM2_DIER,TIMX_DIER_CC1IE))
#define TIMER2_CC2_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM2_DIER,TIMX_DIER_CC2IE))
#define TIMER2_CC3_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM2_DIER,TIMX_DIER_CC3IE))
#define TIMER2_CC4_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM2_DIER,TIMX_DIER_CC4IE))

#define TIMER2_CLEAR_FLAG()                     (CLEAR_BIT_K(TIM2_SR,TIMX_SR_UIF))
#define TIMER2_CCP1_CLEAR_FLAG()                (CLEAR_BIT_K(TIM2_SR,TIMX_SR_CC1IF))
#define TIMER2_CCP2_CLEAR_FLAG()                (CLEAR_BIT_K(TIM2_SR,TIMX_SR_CC2IF))
#define TIMER2_CCP3_CLEAR_FLAG()                (CLEAR_BIT_K(TIM2_SR,TIMX_SR_CC3IF))
#define TIMER2_CCP4_CLEAR_FLAG()                (CLEAR_BIT_K(TIM2_SR,TIMX_SR_CC4IF))

//Timer 3 Interrupts      
#define TIMER3_UPDATE_INTERRUPT_ENABLE()        (SET_BIT_K(TIM3_DIER,TIMX_DIER_UIE))
#define TIMER3_CC1_INTERRUPT_ENABLE()           (SET_BIT_K(TIM3_DIER,TIMX_DIER_CC1IE))
#define TIMER3_CC2_INTERRUPT_ENABLE()           (SET_BIT_K(TIM3_DIER,TIMX_DIER_CC2IE))
#define TIMER3_CC3_INTERRUPT_ENABLE()           (SET_BIT_K(TIM3_DIER,TIMX_DIER_CC3IE))
#define TIMER3_CC4_INTERRUPT_ENABLE()           (SET_BIT_K(TIM3_DIER,TIMX_DIER_CC4IE))

#define TIMER3_UPDATE_INTERRUPT_DISABLE()       (CLEAR_BIT_K(TIM3_DIER,TIMX_DIER_UIE))
#define TIMER3_CC1_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM3_DIER,TIMX_DIER_CC1IE))
#define TIMER3_CC2_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM3_DIER,TIMX_DIER_CC2IE))
#define TIMER3_CC3_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM3_DIER,TIMX_DIER_CC3IE))
#define TIMER3_CC4_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM3_DIER,TIMX_DIER_CC4IE))

#define TIMER3_CLEAR_FLAG()                     (CLEAR_BIT_K(TIM3_SR,TIMX_SR_UIF))
#define TIMER3_CCP1_CLEAR_FLAG()                (CLEAR_BIT_K(TIM3_SR,TIMX_SR_CC1IF))
#define TIMER3_CCP2_CLEAR_FLAG()                (CLEAR_BIT_K(TIM3_SR,TIMX_SR_CC2IF))
#define TIMER3_CCP3_CLEAR_FLAG()                (CLEAR_BIT_K(TIM3_SR,TIMX_SR_CC3IF))
#define TIMER3_CCP4_CLEAR_FLAG()                (CLEAR_BIT_K(TIM3_SR,TIMX_SR_CC4IF))

//Timer 4 Interrupts    
#define TIMER4_UPDATE_INTERRUPT_ENABLE()        (SET_BIT_K(TIM4_DIER,TIMX_DIER_UIE))
#define TIMER4_CC1_INTERRUPT_ENABLE()           (SET_BIT_K(TIM4_DIER,TIMX_DIER_CC1IE))
#define TIMER4_CC2_INTERRUPT_ENABLE()           (SET_BIT_K(TIM4_DIER,TIMX_DIER_CC2IE))
#define TIMER4_CC3_INTERRUPT_ENABLE()           (SET_BIT_K(TIM4_DIER,TIMX_DIER_CC3IE))
#define TIMER4_CC4_INTERRUPT_ENABLE()           (SET_BIT_K(TIM4_DIER,TIMX_DIER_CC4IE))

#define TIMER4_UPDATE_INTERRUPT_DISABLE()       (CLEAR_BIT_K(TIM4_DIER,TIMX_DIER_UIE))
#define TIMER4_CC1_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM4_DIER,TIMX_DIER_CC1IE))
#define TIMER4_CC2_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM4_DIER,TIMX_DIER_CC2IE))
#define TIMER4_CC3_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM4_DIER,TIMX_DIER_CC3IE))
#define TIMER4_CC4_INTERRUPT_DISABLE()          (CLEAR_BIT_K(TIM4_DIER,TIMX_DIER_CC4IE))

#define TIMER4_CLEAR_FLAG()                     (CLEAR_BIT_K(TIM4_SR,TIMX_SR_UIF))
#define TIMER4_CCP1_CLEAR_FLAG()                (CLEAR_BIT_K(TIM4_SR,TIMX_SR_CC1IF))
#define TIMER4_CCP2_CLEAR_FLAG()                (CLEAR_BIT_K(TIM4_SR,TIMX_SR_CC2IF))
#define TIMER4_CCP3_CLEAR_FLAG()                (CLEAR_BIT_K(TIM4_SR,TIMX_SR_CC3IF))
#define TIMER4_CCP4_CLEAR_FLAG()                (CLEAR_BIT_K(TIM4_SR,TIMX_SR_CC4IF))
/*******************MACROS LIKE FUNCTIONS SECTION END  ***********/




/*******************DATA TYPES DECLARATION SECTION START**********/

/*******************DATA TYPES DECLARATION SECTION END  **********/




/*******************FUCNCTIONS PROTOTYPES (APIS) SECTION START****/

/*******************FUCNCTIONS PROTOTYPES (APIS) SECTION END  ****/




#endif

