/**
@file: MCAL_TIMERS_GEN_CFG.h
@author: M4_TEAM 
@creation_date: date
*/

#ifndef MCAL_TIMERS_GEN_CFG_H
#define MCAL_TIMERS_GEN_CFG_H

#define TIMER_FEATURE_ENABLE    (1)
#define TIMER_FEATURE_DISABLE   (0)
#define TIMER_TIMER_MODE       	(0)
#define TIMER_PWM_MODE         	(1)


#define TIMER1_UPDATE_INTERRUPT_FEATURE    	TIMER_FEATURE_ENABLE
#define TIMER1_CCP_INTERRUPT_FEATURE				TIMER_FEATURE_DISABLE
#define TIMER1_MODE                 				TIMER_PWM_MODE

#define TIMER2_UPDATE_INTERRUPT_FEATURE    	TIMER_FEATURE_ENABLE
#define TIMER2_CCP_INTERRUPT_FEATURE				TIMER_FEATURE_DISABLE
#define TIMER2_MODE                 				TIMER_TIMER_MODE

#define TIMER3_UPDATE_INTERRUPT_FEATURE    	TIMER_FEATURE_ENABLE
#define TIMER3_CCP_INTERRUPT_FEATURE				TIMER_FEATURE_DISABLE
#define TIMER3_MODE                 				TIMER_PWM_MODE

#define TIMER4_UPDATE_INTERRUPT_FEATURE    	TIMER_FEATURE_ENABLE
#define TIMER4_CCP_INTERRUPT_FEATURE				TIMER_FEATURE_DISABLE
#define TIMER4_MODE                 				TIMER_TIMER_MODE

#endif

