#include "MCAL_RCC.h"





void RCC_AFIO_CLK_ENABLE(void)
{
	SET_BIT(RCC->APB2ENR,RCC_APB2ENR_AFIOEN);
}	

void RCC_AFIO_CLK_DISABLE(void)
{
	
	CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_AFIOEN);
}	


void RCC_IOPA_CLK_ENABLE(void)
{
	SET_BIT(RCC->APB2ENR,RCC_APB2ENR_IOPAEN);
}	


void RCC_IOPA_CLK_DISABLE(void)
{
	CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_IOPAEN);
}	

void RCC_IOPB_CLK_ENABLE(void)
{
	SET_BIT(RCC->APB2ENR,RCC_APB2ENR_IOPBEN);
}	


void RCC_IOPB_CLK_DISABLE(void)
{
	CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_IOPBEN);
}	
void RCC_IOPC_CLK_ENABLE(void)
{
	SET_BIT(RCC->APB2ENR,RCC_APB2ENR_IOPCEN);
}	


void RCC_IOPC_CLK_DISABLE(void)
{
	CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_IOPCEN);
}	

void RCC_TIM1_CLK_ENABLE(void){
	SET_BIT(RCC->APB2ENR,RCC_APB2ENR_TIM1EN);
}
void RCC_TIM1_CLK_DISABLE(void){
	CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_TIM1EN);
}
void RCC_SPI1_CLK_ENABLE(void){
	SET_BIT(RCC->APB2ENR,RCC_APB2ENR_SPI1EN);
}
void RCC_SPI1_CLK_DISABLE(void){
	CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_SPI1EN);
}
void RCC_USART1_CLK_ENABLE(void){
	SET_BIT(RCC->APB2ENR,RCC_APB2ENR_USART1EN);
}
void RCC_USART1_CLK_DISABLE(void){
	CLEAR_BIT(RCC->APB2ENR,RCC_APB2ENR_USART1EN);
}

void	RCC_TIM2_CLK_ENABLE(void){
	SET_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM2EN);
}
void	RCC_TIM2_CLK_DISABLE(void){
	CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM2EN);
}
void	RCC_TIM3_CLK_ENABLE(void){
	SET_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM3EN);
}
void	RCC_TIM3_CLK_DISABLE(void){
	CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM3EN);
}
void	RCC_TIM4_CLK_ENABLE(void){
	SET_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM4EN);
}
void	RCC_TIM4_CLK_DISABLE(void){
	CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM4EN);
}

void	RCC_USART2_CLK_ENABLE(void){
	SET_BIT(RCC->APB1ENR,RCC_APB1ENR_USART2EN);
}

void	RCC_USART2_CLK_DISABLE(void){
	CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_USART2EN);
}
void	RCC_USART3_CLK_ENABLE(void){
	SET_BIT(RCC->APB1ENR,RCC_APB1ENR_USART3EN);
}
void	RCC_USART3_CLK_DISABLE(void){
	CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_USART3EN);
}
void	RCC_I2C1_CLK_ENABLE(void){
	SET_BIT(RCC->APB1ENR,RCC_APB1ENR_I2C1EN);
}
void	RCC_I2C1_CLK_DISABLE(void){
	CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_I2C1EN);
}
void	RCC_I2C2_CLK_ENABLE(void){
	SET_BIT(RCC->APB1ENR,RCC_APB1ENR_I2C2EN);
}
void	RCC_I2C2_CLK_DISABLE(void){
	CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_I2C2EN);
}
void RCC_SPI2_CLK_ENABLE(void){
	SET_BIT(RCC->APB1ENR,RCC_APB1ENR_SPI2EN);
}
void RCC_SPI2_CLK_DISABLE(void)	{
	CLEAR_BIT(RCC->APB1ENR,RCC_APB1ENR_SPI2EN);
}
