/**
@file: REGISTERS_DEFINITIONS.h
@author: M4_TEAM 
@creation_date: date
*/

#ifndef REGISTERS_DEFINITIONS_H
#define REGISTERS_DEFINITIONS_H


/*******************************INCLUDES SECTION START***********************/
#include "../../stm32f10c8.h"


#include "../std_types.h"


#define BIT_MASK 	((uint32_t)(0x01))

/*******************set,clear,toggle,read macro functions********************/
#define SET_BIT_K(REG,BIT_POS)        			(REG|=(BIT_MASK<<BIT_POS))
#define CLEAR_BIT_K(REG,BIT_POS)      			(REG&=(~(BIT_MASK<<BIT_POS)))
#define READ_BIT_K(REG,BIT_POS)       			((REG>>BIT_POS)&BIT_MASK)   




/**********************************HWRG MACRO FUNCTIONS***************************/
#define HWRG_ADDRESS(BASE_ADDRESS,OFFSET) ((volatile uint32_t *)(BASE_ADDRESS+OFFSET))
#define HWRG(ADDRESS) 										(*ADDRESS)


/*******************************RCC Control Registers Offset**********************/
#define RCC_BASE_ADDRESS 				(0x40021000)
#define RCC_CR_OFFSET 	    		(0x00)
#define RCC_CFGR_OFFSET	    		(0x04)
#define RCC_CIR_OFFSET	    		(0x08)
#define RCC_APB2RSTR_OFFSET			(0x0C)
#define RCC_APB1RSTR_OFFSET			(0x10)
#define RCC_AHBENR_OFFSET				(0x14)
#define RCC_APB2ENR_OFFSET			(0x18)
#define RCC_APB1ENR_OFFSET			(0x1C)
#define RCC_BDCR_OFFSET	    		(0x20)
#define RCC_CSR_OFFSET	    		(0x24)
#define RCC_AHBSTR_OFFSET				(0x28)
#define RCC_CFGR2_OFFSET				(0x2C)


/*****************************RCC Registers Access**************************************/
#define RCC_CR_ADDRESS 					HWRG_ADDRESS(RCC_BASE_ADDRESS,RCC_CR_OFFSET )
#define RCC_CR									HWRG(RCC_CR_ADDRESS)

#define RCC_CFGR_ADDRESS				HWRG_ADDRESS(RCC_BASE_ADDRESS,RCC_CFGR_OFFSET)
#define RCC_CFGR								HWRG(RCC_CFGR_ADDRESS)

#define RCC_CIR_ADDRESS					HWRG_ADDRESS(RCC_BASE_ADDRESS,RCC_CIR_OFFSET)
#define RCC_CIR									HWRG(RCC_CIR_ADDRESS)

#define RCC_APB2RSTR_ADDRESS		HWRG_ADDRESS(RCC_BASE_ADDRESS,RCC_APB2RSTR_OFFSET)
#define RCC_APB2RSTR						HWRG(RCC_APB2RSTR_ADDRESS)

#define RCC_APB1RSTR_ADDRESS		HWRG_ADDRESS(RCC_BASE_ADDRESS,RCC_APB1RSTR_OFFSET)
#define RCC_APB1RSTR						HWRG(RCC_APB1RSTR_ADDRESS)

#define RCC_AHBENR_ADDRESS			HWRG_ADDRESS(RCC_BASE_ADDRESS,RCC_AHBENR_OFFSET)
#define RCC_AHBENR							HWRG(RCC_AHBENR_ADDRESS)

#define RCC_APB2ENR_ADDRESS			HWRG_ADDRESS(RCC_BASE_ADDRESS,RCC_APB2ENR_OFFSET)
#define RCC_APB2ENR							HWRG(RCC_APB2ENR_ADDRESS)

#define RCC_APB1ENR_ADDRESS			HWRG_ADDRESS(RCC_BASE_ADDRESS,RCC_APB1ENR_OFFSET)
#define RCC_APB1ENR							HWRG(RCC_APB1ENR_ADDRESS)

#define RCC_BDCR_ADDRESS				HWRG_ADDRESS(RCC_BASE_ADDRESS,RCC_BDCR_OFFSET)
#define RCC_BDCR								HWRG(RCC_BDCR_ADDRESS)

#define RCC_CSR_ADDRESS					HWRG_ADDRESS(RCC_BASE_ADDRESS,RCC_CSR_OFFSET)
#define RCC_CSR									HWRG(RCC_CSR_ADDRESS)

#define RCC_AHBSTR_ADDRESS			HWRG_ADDRESS(RCC_BASE_ADDRESS,RCC_AHBSTR_OFFSET)
#define RCC_AHBSTR							HWRG(RCC_AHBSTR_ADDRESS)

#define RCC_CFGR2_ADDRESS				HWRG_ADDRESS(RCC_BASE_ADDRESS,RCC_CFGR2_OFFSET)
#define RCC_CFGR2								HWRG(RCC_CFGR2_ADDRESS)


/*************RCC_APB2ENR Bitfields*********************/
#define RCC_APB2ENR_AFIO_EN			(0)
#define RCC_APB2ENR_IOPA_EN			(2)
#define RCC_APB2ENR_IOPB_EN			(3)
#define RCC_APB2ENR_IOPC_EN			(4)
#define RCC_APB2ENR_TIM1_EN			(11)
#define RCC_APB2ENR_SPI1_EN			(12)
#define RCC_APB2ENR_USART1_EN		(14)

/*************RCC_APB1ENR Bitfields*********************/
#define RCC_APB1ENR_TIM2_EN			(0)
#define RCC_APB1ENR_TIM3_EN			(1)
#define RCC_APB1ENR_TIM4_EN			(2)
#define RCC_APB1ENR_SPI2_EN			(14)
#define RCC_APB1ENR_USART2_EN		(17)
#define RCC_APB1ENR_USART3_EN		(18)
#define RCC_APB1ENR_I2C1_EN			(21)
#define RCC_APB1ENR_I2C2_EN			(22)














/*******************************GPIOX Control Registers Offset**********************/
#define GPIOA_BASE_ADDRESS 			(0x40010800)
#define GPIOB_BASE_ADDRESS			(0x40010C00)
#define GPIOC_BASE_ADDRESS 			(0x40011000)
#define GPIOX_CRL_OFFSET 				(0x00)
#define GPIOX_CRH_OFFSET				(0x04)
#define GPIOX_IDR_OFFSET				(0x08)
#define GPIOX_ODR_OFFSET				(0x0C)
#define GPIOX_BSRR_OFFSET				(0x10)
#define GPIOX_BRR_OFFSET				(0x14)
#define GPIOX_LCKR_OFFSET				(0x18)



/*******************************GPIOA Registers Access*****************************/
#define GPIOA_CRL_ADDRESS					HWRG_ADDRESS(GPIOA_BASE_ADDRESS,GPIOX_CRL_OFFSET)
#define GPIOA_CRL									HWRG(GPIOA_CRL_ADDRESS)

#define GPIOA_CRH_ADDRESS					HWRG_ADDRESS(GPIOA_BASE_ADDRESS,GPIOX_CRH_OFFSET)
#define GPIOA_CRH									HWRG(GPIOA_CRH_ADDRESS)

#define GPIOA_IDR_ADDRESS					HWRG_ADDRESS(GPIOA_BASE_ADDRESS,GPIOX_IDR_OFFSET)
#define GPIOA_IDR									HWRG(GPIOA_IDR_ADDRESS)

#define GPIOA_ODR_ADDRESS					HWRG_ADDRESS(GPIOA_BASE_ADDRESS,GPIOX_ODR_OFFSET)
#define GPIOA_ODR									HWRG(GPIOA_ODR_ADDRESS)

#define GPIOA_BSRR_ADDRESS				HWRG_ADDRESS(GPIOA_BASE_ADDRESS,GPIOX_BSRR_OFFSET)
#define GPIOA_BSRR								HWRG(GPIOA_BSRR_ADDRESS)

#define GPIOA_BRR_ADDRESS					HWRG_ADDRESS(GPIOA_BASE_ADDRESS,GPIOX_BRR_OFFSET)
#define GPIOA_BRR									HWRG(GPIOA_BRR_ADDRESS)

#define GPIOA_LCKR_ADDRESS				HWRG_ADDRESS(GPIOA_BASE_ADDRESS,GPIOX_LCKR_OFFSET)
#define GPIOA_LCKR								HWRG(GPIOA_LCKR_ADDRESS)


/*******************************GPIOB REGISTERS Access*****************************/
#define GPIOB_CRL_ADDRESS					HWRG_ADDRESS(GPIOB_BASE_ADDRESS,GPIOX_CRL_OFFSET)
#define GPIOB_CRL									HWRG(GPIOB_CRL_ADDRESS)

#define GPIOB_CRH_ADDRESS					HWRG_ADDRESS(GPIOB_BASE_ADDRESS,GPIOX_CRH_OFFSET)
#define GPIOB_CRH									HWRG(GPIOB_CRH_ADDRESS)

#define GPIOB_IDR_ADDRESS					HWRG_ADDRESS(GPIOB_BASE_ADDRESS,GPIOX_IDR_OFFSET)
#define GPIOB_IDR									HWRG(GPIOB_IDR_ADDRESS)

#define GPIOB_ODR_ADDRESS					HWRG_ADDRESS(GPIOB_BASE_ADDRESS,GPIOX_ODR_OFFSET)
#define GPIOB_ODR									HWRG(GPIOB_ODR_ADDRESS)

#define GPIOB_BSRR_ADDRESS				HWRG_ADDRESS(GPIOB_BASE_ADDRESS,GPIOX_BSRR_OFFSET)
#define GPIOB_BSRR								HWRG(GPIOB_BSRR_ADDRESS)

#define GPIOB_BRR_ADDRESS					HWRG_ADDRESS(GPIOB_BASE_ADDRESS,GPIOX_BRR_OFFSET)
#define GPIOB_BRR									HWRG(GPIOB_BRR_ADDRESS)

#define GPIOB_LCKR_ADDRESS				HWRG_ADDRESS(GPIOB_BASE_ADDRESS,GPIOX_LCKR_OFFSET)
#define GPIOB_LCKR								HWRG(GPIOB_LCKR_ADDRESS)


/*******************************GPIOC REGISTERS Access*****************************/
#define GPIOC_CRL_ADDRESS				HWRG_ADDRESS(GPIOC_BASE_ADDRESS,GPIOX_CRL_OFFSET)
#define GPIOC_CRL								HWRG(GPIOC_CRL_ADDRESS)

#define GPIOC_CRH_ADDRESS				HWRG_ADDRESS(GPIOC_BASE_ADDRESS,GPIOX_CRH_OFFSET)
#define GPIOC_CRH								HWRG(GPIOC_CRH_ADDRESS)

#define GPIOC_IDR_ADDRESS				HWRG_ADDRESS(GPIOC_BASE_ADDRESS,GPIOX_IDR_OFFSET)
#define GPIOC_IDR								HWRG(GPIOC_IDR_ADDRESS)

#define GPIOC_ODR_ADDRESS				HWRG_ADDRESS(GPIOC_BASE_ADDRESS,GPIOX_ODR_OFFSET)
#define GPIOC_ODR								HWRG(GPIOC_ODR_ADDRESS)

#define GPIOC_BSRR_ADDRESS			HWRG_ADDRESS(GPIOC_BASE_ADDRESS,GPIOX_BSRR_OFFSET)
#define GPIOC_BSRR							HWRG(GPIOC_BSRR_ADDRESS)

#define GPIOC_BRR_ADDRESS				HWRG_ADDRESS(GPIOC_BASE_ADDRESS,GPIOX_BRR_OFFSET)
#define GPIOC_BRR								HWRG(GPIOC_BRR_ADDRESS)

#define GPIOC_LCKR_ADDRESS			HWRG_ADDRESS(GPIOC_BASE_ADDRESS,GPIOX_LCKR_OFFSET)
#define GPIOC_LCKR							HWRG(GPIOC_LCKR_ADDRESS)




#define CRL_MAX_PIN_INDEX 			(7)
#define CRH_MAX_PIN_INDEX 			(15)











/**********************************AFIO REGISTERS OFFSET************************************/
#define AFIO_BASE_ADDRESS 				(0x40010000)
#define AFIO_EVCR_OFFSET 					(0x00)
#define AFIO_MAPR_OFFSET 					(0x04)
#define AFIO_EXTICR1_OFFSET 			(0x08)
#define AFIO_EXTICR2_OFFSET 			(0x0C)
#define AFIO_EXTICR3_OFFSET 			(0x10)
#define AFIO_EXTICR4_OFFSET 			(0x14)
#define AFIO_MAPR2_OFFSET 				(0x1C)


/*******************************AFIO Registers Acess ****************************/

#define AFIO_EVCR_ADDRESS     HWRG_ADDRESS(AFIO_BASE_ADDRESS,AFIO_EVCR_OFFSET)
#define AFIO_EVCR							HWRG(AFIO_EVCR_ADDRESS)
#define AFIO_EXTICR1_ADDRESS  HWRG_ADDRESS(AFIO_BASE_ADDRESS,AFIO_EXTICR1_OFFSET)
#define AFIO_EXTICR1					HWRG(AFIO_EXTICR1_ADDRESS)
#define AFIO_EXTICR2_ADDRESS  HWRG_ADDRESS(AFIO_BASE_ADDRESS,AFIO_EXTICR2_OFFSET)
#define AFIO_EXTICR2					HWRG(AFIO_EXTICR2_ADDRESS)
#define AFIO_EXTICR3_ADDRESS  HWRG_ADDRESS(AFIO_BASE_ADDRESS,AFIO_EXTICR3_OFFSET)
#define AFIO_EXTICR3					HWRG(AFIO_EXTICR3_ADDRESS)
#define AFIO_EXTICR4_ADDRESS  HWRG_ADDRESS(AFIO_BASE_ADDRESS,AFIO_EXTICR4_OFFSET)
#define AFIO_EXTICR4					HWRG(AFIO_EXTICR4_ADDRESS)












/*******************************External INTERRUPT Registers Offset**********************/
#define EXTI_BASE_ADDRESS 							(0x40010400)
#define EXTI_IMR_OFFSET									(0x00)
#define EXTI_EMR_OFFSET									(0x04)
#define EXTI_RTSR_OFFSET								(0x08)
#define EXTI_FTSR_OFFSET								(0x0C)
#define EXTI_SWIER_OFFSET								(0x10)
#define EXTI_PR_OFFSET									(0x14)



/*******************************External INTERRUPT Registers Acess****************************/
#define EXTI_IMR_ADDRESS     	HWRG_ADDRESS(EXTI_BASE_ADDRESS,EXTI_IMR_OFFSET)
#define EXTI_IMR							HWRG(EXTI_IMR_ADDRESS)
#define EXTI_EMR_ADDRESS     	HWRG_ADDRESS(EXTI_BASE_ADDRESS,EXTI_EMR_OFFSET)
#define EXTI_EMR							HWRG(EXTI_EMR_ADDRESS)
#define EXTI_RTSR_ADDRESS     HWRG_ADDRESS(EXTI_BASE_ADDRESS,EXTI_RTSR_OFFSET)
#define EXTI_RTSR							HWRG(EXTI_RTSR_ADDRESS)
#define EXTI_FTSR_ADDRESS     HWRG_ADDRESS(EXTI_BASE_ADDRESS,EXTI_FTSR_OFFSET)
#define EXTI_FTSR							HWRG(EXTI_FTSR_ADDRESS)
#define EXTI_PR_ADDRESS     	HWRG_ADDRESS(EXTI_BASE_ADDRESS,EXTI_PR_OFFSET)
#define EXTI_PR								HWRG(EXTI_PR_ADDRESS)
#define EXTI_SWIER_ADDRESS     	HWRG_ADDRESS(EXTI_BASE_ADDRESS,EXTI_SWIER_OFFSET)
#define EXTI_SWIER								HWRG(EXTI_SWIER_ADDRESS)

//EXTI_IMR BIT FIELD
#define MR0			(0)
#define MR1			(1)
#define MR2			(2)
#define MR3			(3)
#define MR4			(4)
#define MR5			(5)
#define MR6			(6)
#define MR7			(7)
#define MR8			(8)
#define MR9			(9)
#define MR10		(10)
#define MR11		(11)
#define MR12		(12)
#define MR13		(13)
#define MR14		(14)
#define MR15		(15)
#define MR16		(16)
#define MR17		(17)
#define MR18		(18)
#define MR19		(19)


//EXTI_RTSR BIT FIELD
#define TR0			(0)
#define TR1			(1)
#define TR2			(2)
#define TR3			(3)
#define TR4			(4)
#define TR5			(5)
#define TR6			(6)
#define TR7			(7)
#define TR8			(8)
#define TR9			(9)
#define TR10		(10)
#define TR11		(11)
#define TR12		(12)
#define TR13		(13)
#define TR14		(14)
#define TR15		(15)
#define TR16		(16)
#define TR17		(17)
#define TR18		(18)
#define TR19		(19)


//EXTI_PR BIT FIELD
#define PR0			(0)
#define PR1			(1)
#define PR2			(2)
#define PR3			(3)
#define PR4			(4)
#define PR5			(5)
#define PR6			(6)
#define PR7			(7)
#define PR8			(8)
#define PR9			(9)
#define PR10		(10)
#define PR11		(11)
#define PR12		(12)
#define PR13		(13)
#define PR14		(14)
#define PR15		(15)
#define PR16		(16)
#define PR17		(17)
#define PR18		(18)
#define PR19		(19)










/*******************************NVIC Registers Offset**********************/
#define NVIC_BASE_ADDRESS 			(0xE000E100)
#define NVIC_ISER0_OFFSET				(0x00)
#define NVIC_ISER1_OFFSET				(0x004)
#define NVIC_ISER2_OFFSET				(0x008)
#define NVIC_ICER0_OFFSET				(0x080)
#define NVIC_ICER1_OFFSET				(0x084)
#define NVIC_ICER2_OFFSET				(0x088)
#define NVIC_ISPR0_OFFSET				(0x100)
#define NVIC_ISPR1_OFFSET				(0x104)
#define NVIC_ISPR2_OFFSET				(0x108)
#define NVIC_ICPR0_OFFSET				(0x180)
#define NVIC_ICPR1_OFFSET				(0x184)
#define NVIC_ICPR2_OFFSET				(0x188)
#define NVIC_IABR0_OFFSET				(0x200)
#define NVIC_IABR1_OFFSET				(0x204)
#define NVIC_IABR2_OFFSET				(0x208)
#define NVIC_IPR0_OFFSET				(0x300)

/********CONTINUE PRIORITY*******/

#define NVIC_STIR_OFFSET				(0xE00)
/*******************************NVIC Registers Access ****************************/

#define NVIC_ISER0_ADDRESS     	HWRG_ADDRESS(NVIC_BASE_ADDRESS,NVIC_ISER0_OFFSET)
#define NVIC_ISER0							HWRG(NVIC_ISER0_ADDRESS)
#define NVIC_ISER1_ADDRESS     	HWRG_ADDRESS(NVIC_BASE_ADDRESS,NVIC_ISER1_OFFSET)
#define NVIC_ISER1							HWRG(NVIC_ISER1_ADDRESS)
#define NVIC_ISER2_ADDRESS     	HWRG_ADDRESS(NVIC_BASE_ADDRESS,NVIC_ISER2_OFFSET)
#define NVIC_ISER2							HWRG(NVIC_ISER2_ADDRESS)
#define NVIC_ICER0_ADDRESS     	HWRG_ADDRESS(NVIC_BASE_ADDRESS,NVIC_ICER0_OFFSET)
#define NVIC_ICER0							HWRG(NVIC_ICER0_ADDRESS)
#define NVIC_ICER1_ADDRESS     	HWRG_ADDRESS(NVIC_BASE_ADDRESS,NVIC_ICER1_OFFSET)
#define NVIC_ICER1							HWRG(NVIC_ICER1_ADDRESS)
#define NVIC_ICER2_ADDRESS     	HWRG_ADDRESS(NVIC_BASE_ADDRESS,NVIC_ICER2_OFFSET)
#define NVIC_ICER2							HWRG(NVIC_ICER2_ADDRESS)
#define NVIC_ICPR0_ADDRESS     	HWRG_ADDRESS(NVIC_BASE_ADDRESS,NVIC_ICPR0_OFFSET)
#define NVIC_ICPR0							HWRG(NVIC_ICPR0_ADDRESS)
#define NVIC_ICPR1_ADDRESS     	HWRG_ADDRESS(NVIC_BASE_ADDRESS,NVIC_ICPR1_OFFSET)
#define NVIC_ICPR1							HWRG(NVIC_ICPR1_ADDRESS)
#define NVIC_ICPR2_ADDRESS     	HWRG_ADDRESS(NVIC_BASE_ADDRESS,NVIC_ICPR2_OFFSET)
#define NVIC_ICPR2							HWRG(NVIC_ICPR2_ADDRESS)
#define NVIC_ISPR0_ADDRESS     	HWRG_ADDRESS(NVIC_BASE_ADDRESS,NVIC_ISPR0_OFFSET)
#define NVIC_ISPR0							HWRG(NVIC_ISPR0_ADDRESS)
#define NVIC_ISPR1_ADDRESS     	HWRG_ADDRESS(NVIC_BASE_ADDRESS,NVIC_ISPR1_OFFSET)
#define NVIC_ISPR1							HWRG(NVIC_ISPR1_ADDRESS)
#define NVIC_ISPR2_ADDRESS     	HWRG_ADDRESS(NVIC_BASE_ADDRESS,NVIC_ISPR2_OFFSET)
#define NVIC_ISPR2							HWRG(NVIC_ISPR2_ADDRESS)


//NVIC BITFIELDS



/*******************************General Purpose Timers Registers Offset**********************/
#define TIMER1_BASE_ADDRESS 			(0x40012C00)
#define TIMER2_BASE_ADDRESS 			(0x40000000)
#define TIMER3_BASE_ADDRESS 			(0x40000400)
#define TIMER4_BASE_ADDRESS 			(0x40000800)
#define TIMx_CR1_OFFSET						(0x00)
#define TIMx_CR2_OFFSET						(0x04)
#define TIMx_SMCR_OFFSET					(0x08)
#define TIMx_DIER_OFFSET					(0x0C)
#define TIMx_SR_OFFSET						(0x10)
#define TIMx_EGR_OFFSET						(0x14)
#define TIMx_CCMR1_OFFSET					(0x18)
#define TIMx_CCMR2_OFFSET					(0x1C)
#define TIMx_CCER_OFFSET					(0x20)
#define TIMx_CNT_OFFSET						(0x24)
#define TIMx_PSC_OFFSET						(0x28)
#define TIMx_ARR_OFFSET						(0x2C)
#define TIMx_CCR1_OFFSET					(0x34)
#define TIMx_CCR2_OFFSET					(0x38)
#define TIMx_CCR3_OFFSET					(0x3C)
#define TIMx_CCR4_OFFSET					(0x40)
#define TIMx_BDTR_OFFSET					(0x44)
#define TIMx_DCR_OFFSET						(0x48)
#define TIMx_DMAR_OFFSET					(0x4C)



/*******************************General Purpose	Timers Registers Access ****************************/
//TIMER1
#define TIM1_CR1_ADDRESS     	HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_CR1_OFFSET)
#define TIM1_CR1							HWRG(TIM1_CR1_ADDRESS)
#define TIM1_CR2_ADDRESS     	HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_CR2_OFFSET)
#define TIM1_CR2							HWRG(TIM1_CR2_ADDRESS)
#define TIM1_SMCR_ADDRESS     HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_SMCR_OFFSET)
#define TIM1_SMCR							HWRG(TIM1_SMCR_ADDRESS)
#define TIM1_DIER_ADDRESS     HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_DIER_OFFSET)
#define TIM1_DIER							HWRG(TIM1_DIER_ADDRESS)
#define TIM1_SR_ADDRESS     	HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_SR_OFFSET)
#define TIM1_SR								HWRG(TIM1_SR_ADDRESS)
#define TIM1_EGR_ADDRESS     	HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_EGR_OFFSET)
#define TIM1_EGR							HWRG(TIM1_EGR_ADDRESS)
#define TIM1_CCMR1_ADDRESS    HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_CCMR1_OFFSET)
#define TIM1_CCMR1						HWRG(TIM1_CCMR1_ADDRESS)
#define TIM1_CCMR2_ADDRESS    HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_CCMR2_OFFSET)
#define TIM1_CCMR2						HWRG(TIM1_CCMR2_ADDRESS)
#define TIM1_CCER_ADDRESS     HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_CCER_OFFSET)
#define TIM1_CCER							HWRG(TIM1_CCER_ADDRESS)
#define TIM1_CNT_ADDRESS     	HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_CNT_OFFSET)
#define TIM1_CNT							HWRG(TIM1_CNT_ADDRESS)
#define TIM1_PSC_ADDRESS     	HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_PSC_OFFSET)
#define TIM1_PSC							HWRG(TIM1_PSC_ADDRESS)
#define TIM1_ARR_ADDRESS     	HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_ARR_OFFSET)
#define TIM1_ARR							HWRG(TIM1_ARR_ADDRESS)
#define TIM1_CCR1_ADDRESS     HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_CCR1_OFFSET)
#define TIM1_CCR1							HWRG(TIM1_CCR1_ADDRESS)
#define TIM1_CCR2_ADDRESS     HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_CCR2_OFFSET)
#define TIM1_CCR2							HWRG(TIM1_CCR2_ADDRESS)
#define TIM1_CCR3_ADDRESS    	HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_CCR3_OFFSET)
#define TIM1_CCR3							HWRG(TIM1_CCR3_ADDRESS)
#define TIM1_CCR4_ADDRESS    	HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_CCR4_OFFSET)
#define TIM1_CCR4							HWRG(TIM1_CCR4_ADDRESS)
#define TIM1_BDTR_ADDRESS    	HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_BDTR_OFFSET)
#define TIM1_BDTR							HWRG(TIM1_BDTR_ADDRESS)
#define TIM1_DCR_ADDRESS     	HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_DCR_OFFSET)
#define TIM1_DCR							HWRG(TIM1_DCR_ADDRESS)
#define TIM1_DMAR_ADDRESS    	HWRG_ADDRESS(TIMER1_BASE_ADDRESS,TIMx_DMAR_OFFSET)
#define TIM1_DMAR							HWRG(TIM1_DMAR_ADDRESS)



//TIMER2
#define TIM2_CR1_ADDRESS     	HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_CR1_OFFSET)
#define TIM2_CR1							HWRG(TIM2_CR1_ADDRESS)
#define TIM2_CR2_ADDRESS     	HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_CR2_OFFSET)
#define TIM2_CR2							HWRG(TIM2_CR2_ADDRESS)
#define TIM2_SMCR_ADDRESS     HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_SMCR_OFFSET)
#define TIM2_SMCR							HWRG(TIM2_SMCR_ADDRESS)
#define TIM2_DIER_ADDRESS     HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_DIER_OFFSET)
#define TIM2_DIER							HWRG(TIM2_DIER_ADDRESS)
#define TIM2_SR_ADDRESS     	HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_SR_OFFSET)
#define TIM2_SR								HWRG(TIM2_SR_ADDRESS)
#define TIM2_EGR_ADDRESS     	HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_EGR_OFFSET)
#define TIM2_EGR							HWRG(TIM2_EGR_ADDRESS)
#define TIM2_CCMR1_ADDRESS    HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_CCMR1_OFFSET)
#define TIM2_CCMR1						HWRG(TIM2_CCMR1_ADDRESS)
#define TIM2_CCMR2_ADDRESS    HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_CCMR2_OFFSET)
#define TIM2_CCMR2						HWRG(TIM2_CCMR2_ADDRESS)
#define TIM2_CCER_ADDRESS     HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_CCER_OFFSET)
#define TIM2_CCER							HWRG(TIM2_CCER_ADDRESS)
#define TIM2_CNT_ADDRESS     	HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_CNT_OFFSET)
#define TIM2_CNT							HWRG(TIM2_CNT_ADDRESS)
#define TIM2_PSC_ADDRESS     	HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_PSC_OFFSET)
#define TIM2_PSC							HWRG(TIM2_PSC_ADDRESS)
#define TIM2_ARR_ADDRESS     	HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_ARR_OFFSET)
#define TIM2_ARR							HWRG(TIM2_ARR_ADDRESS)
#define TIM2_CCR1_ADDRESS     HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_CCR1_OFFSET)
#define TIM2_CCR1							HWRG(TIM2_CCR1_ADDRESS)
#define TIM2_CCR2_ADDRESS     HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_CCR2_OFFSET)
#define TIM2_CCR2							HWRG(TIM2_CCR2_ADDRESS)
#define TIM2_CCR3_ADDRESS    	HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_CCR3_OFFSET)
#define TIM2_CCR3							HWRG(TIM2_CCR3_ADDRESS)
#define TIM2_CCR4_ADDRESS    	HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_CCR4_OFFSET)
#define TIM2_CCR4							HWRG(TIM2_CCR4_ADDRESS)
#define TIM2_DCR_ADDRESS     	HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_DCR_OFFSET)
#define TIM2_DCR							HWRG(TIM2_DCR_ADDRESS)
#define TIM2_DMAR_ADDRESS    	HWRG_ADDRESS(TIMER2_BASE_ADDRESS,TIMx_DMAR_OFFSET)
#define TIM2_DMAR							HWRG(TIM2_DMAR_ADDRESS)



//TIMER3
#define TIM3_CR1_ADDRESS     	HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_CR1_OFFSET)
#define TIM3_CR1							HWRG(TIM3_CR1_ADDRESS)
#define TIM3_CR2_ADDRESS     	HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_CR2_OFFSET)
#define TIM3_CR2							HWRG(TIM3_CR2_ADDRESS)
#define TIM3_SMCR_ADDRESS     HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_SMCR_OFFSET)
#define TIM3_SMCR							HWRG(TIM3_SMCR_ADDRESS)
#define TIM3_DIER_ADDRESS     HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_DIER_OFFSET)
#define TIM3_DIER							HWRG(TIM3_DIER_ADDRESS)
#define TIM3_SR_ADDRESS     	HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_SR_OFFSET)
#define TIM3_SR								HWRG(TIM3_SR_ADDRESS)
#define TIM3_EGR_ADDRESS     	HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_EGR_OFFSET)
#define TIM3_EGR							HWRG(TIM3_EGR_ADDRESS)
#define TIM3_CCMR1_ADDRESS    HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_CCMR1_OFFSET)
#define TIM3_CCMR1						HWRG(TIM3_CCMR1_ADDRESS)
#define TIM3_CCMR2_ADDRESS    HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_CCMR2_OFFSET)
#define TIM3_CCMR2						HWRG(TIM3_CCMR2_ADDRESS)
#define TIM3_CCER_ADDRESS     HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_CCER_OFFSET)
#define TIM3_CCER							HWRG(TIM3_CCER_ADDRESS)
#define TIM3_CNT_ADDRESS     	HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_CNT_OFFSET)
#define TIM3_CNT							HWRG(TIM3_CNT_ADDRESS)
#define TIM3_PSC_ADDRESS     	HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_PSC_OFFSET)
#define TIM3_PSC							HWRG(TIM3_PSC_ADDRESS)
#define TIM3_ARR_ADDRESS     	HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_ARR_OFFSET)
#define TIM3_ARR							HWRG(TIM3_ARR_ADDRESS)
#define TIM3_CCR1_ADDRESS     HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_CCR1_OFFSET)
#define TIM3_CCR1							HWRG(TIM3_CCR1_ADDRESS)
#define TIM3_CCR2_ADDRESS     HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_CCR2_OFFSET)
#define TIM3_CCR2							HWRG(TIM3_CCR2_ADDRESS)
#define TIM3_CCR3_ADDRESS    	HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_CCR3_OFFSET)
#define TIM3_CCR3							HWRG(TIM3_CCR3_ADDRESS)
#define TIM3_CCR4_ADDRESS    	HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_CCR4_OFFSET)
#define TIM3_CCR4							HWRG(TIM3_CCR4_ADDRESS)
#define TIM3_DCR_ADDRESS     	HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_DCR_OFFSET)
#define TIM3_DCR							HWRG(TIM3_DCR_ADDRESS)
#define TIM3_DMAR_ADDRESS    	HWRG_ADDRESS(TIMER3_BASE_ADDRESS,TIMx_DMAR_OFFSET)
#define TIM3_DMAR							HWRG(TIM3_DMAR_ADDRESS)



//TIMER4
#define TIM4_CR1_ADDRESS     	HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_CR1_OFFSET)
#define TIM4_CR1							HWRG(TIM4_CR1_ADDRESS)
#define TIM4_CR2_ADDRESS     	HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_CR2_OFFSET)
#define TIM4_CR2							HWRG(TIM4_CR2_ADDRESS)
#define TIM4_SMCR_ADDRESS     HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_SMCR_OFFSET)
#define TIM4_SMCR							HWRG(TIM4_SMCR_ADDRESS)
#define TIM4_DIER_ADDRESS     HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_DIER_OFFSET)
#define TIM4_DIER							HWRG(TIM4_DIER_ADDRESS)
#define TIM4_SR_ADDRESS     	HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_SR_OFFSET)
#define TIM4_SR								HWRG(TIM4_SR_ADDRESS)
#define TIM4_EGR_ADDRESS     	HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_EGR_OFFSET)
#define TIM4_EGR							HWRG(TIM4_EGR_ADDRESS)
#define TIM4_CCMR1_ADDRESS    HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_CCMR1_OFFSET)
#define TIM4_CCMR1						HWRG(TIM4_CCMR1_ADDRESS)
#define TIM4_CCMR2_ADDRESS    HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_CCMR2_OFFSET)
#define TIM4_CCMR2						HWRG(TIM4_CCMR2_ADDRESS)
#define TIM4_CCER_ADDRESS     HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_CCER_OFFSET)
#define TIM4_CCER							HWRG(TIM4_CCER_ADDRESS)
#define TIM4_CNT_ADDRESS     	HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_CNT_OFFSET)
#define TIM4_CNT							HWRG(TIM4_CNT_ADDRESS)
#define TIM4_PSC_ADDRESS     	HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_PSC_OFFSET)
#define TIM4_PSC							HWRG(TIM4_PSC_ADDRESS)
#define TIM4_ARR_ADDRESS     	HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_ARR_OFFSET)
#define TIM4_ARR							HWRG(TIM4_ARR_ADDRESS)
#define TIM4_CCR1_ADDRESS     HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_CCR1_OFFSET)
#define TIM4_CCR1							HWRG(TIM4_CCR1_ADDRESS)
#define TIM4_CCR2_ADDRESS     HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_CCR2_OFFSET)
#define TIM4_CCR2							HWRG(TIM4_CCR2_ADDRESS)
#define TIM4_CCR3_ADDRESS    	HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_CCR3_OFFSET)
#define TIM4_CCR3							HWRG(TIM4_CCR3_ADDRESS)
#define TIM4_CCR4_ADDRESS    	HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_CCR4_OFFSET)
#define TIM4_CCR4							HWRG(TIM4_CCR4_ADDRESS)
#define TIM4_DCR_ADDRESS     	HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_DCR_OFFSET)
#define TIM4_DCR							HWRG(TIM4_DCR_ADDRESS)
#define TIM4_DMAR_ADDRESS    	HWRG_ADDRESS(TIMER4_BASE_ADDRESS,TIMx_DMAR_OFFSET)
#define TIM4_DMAR							HWRG(TIM4_DMAR_ADDRESS)

/*******************************General Purpose	Timers BitFields ****************************/
//TIMX_CR1 BITS
#define TIMX_CR1_CEN			(0)
#define TIMX_CR1_UDIS			(1)
#define TIMX_CR1_URS			(2)
#define TIMX_CR1_OPM			(3)
#define TIMX_CR1_DIR			(4)
#define TIMX_CR1_CMS_0		(5)
#define TIMX_CR1_CMS_1		(6)
#define TIMX_CR1_ARPE			(7)
#define TIMX_CR1_CKD_0		(8)
#define TIMX_CR1_CKD_1		(8)

//TIMX_CR2 BITS
#define TIMX_CR2_CCDS			(3)
#define TIMX_CR2_MMS_0		(4)
#define TIMX_CR2_MMS_1		(5)
#define TIMX_CR2_MMS_2		(6)
#define TIMX_CR2_T1IS			(7)

//TIMX_DIER BITS
#define TIMX_DIER_UIE			(0)
#define TIMX_DIER_CC1IE		(1)
#define TIMX_DIER_CC2IE		(2)
#define TIMX_DIER_CC3IE		(3)
#define TIMX_DIER_CC4IE		(4)
#define TIMX_DIER_TIE			(6)
#define TIMX_DIER_UDE			(8)
#define TIMX_DIER_CC1DE		(9)
#define TIMX_DIER_CC2DE		(10)
#define TIMX_DIER_CC3DE		(11)
#define TIMX_DIER_CC4DE		(12)
#define TIMX_DIER_TDE			(14)


//TIMX_SR BITS
#define TIMX_SR_UIF				(0)
#define TIMX_SR_CC1IF			(1)
#define TIMX_SR_CC2IF			(2)
#define TIMX_SR_CC3IF			(3)
#define TIMX_SR_CC4IF			(4)
#define TIMX_SR_TIF				(6)
#define TIMX_SR_CC1OF			(9)
#define TIMX_SR_CC2OF			(10)
#define TIMX_SR_CC3OF			(11)
#define TIMX_SR_CC4OF			(12)


//TIMX_EGR BITS
#define TIMX_EGR_UG               (0)
#define TIMX_EGR_CC1G             (1)
#define TIMX_EGR_CC2G             (2)
#define TIMX_EGR_CC3G             (3)
#define TIMX_EGR_CC4G             (4)
#define TIMX_EGR_TG               (6)




//TIMX_CCMR1 BITS
#define TIMX_CCMR1_CC1S_0		(0)
#define TIMX_CCMR1_CC1S_1		(1)
#define TIMX_CCMR1_IC1PSC_0	(2)
#define TIMX_CCMR1_IC1PSC_1	(3)
#define TIMX_CCMR1_OC1FE	(2)
#define TIMX_CCMR1_OC1PE	(3)
#define TIMX_CCMR1_IC1F_0		(4)
#define TIMX_CCMR1_IC1F_1		(5)
#define TIMX_CCMR1_IC1F_2		(6)
#define TIMX_CCMR1_IC1F_3		(7)
#define TIMX_CCMR1_OC1M_0		(4)
#define TIMX_CCMR1_OC1M_1		(5)
#define TIMX_CCMR1_OC1M_2		(6)
#define TIMX_CCMR1_OC1CE		(7)
#define TIMX_CCMR1_CC2S_0		(8)
#define TIMX_CCMR1_CC2S_1		(9)
#define TIMX_CCMR1_IC2PSC_0	(10)
#define TIMX_CCMR1_IC2PSC_1	(11)
#define TIMX_CCMR1_OC2FE	(10)
#define TIMX_CCMR1_OC2PE	(11)
#define TIMX_CCMR1_IC2F_0		(12)
#define TIMX_CCMR1_IC2F_1		(13)
#define TIMX_CCMR1_IC2F_2		(14)
#define TIMX_CCMR1_IC2F_3		(15)
#define TIMX_CCMR1_OC2M_0		(12)
#define TIMX_CCMR1_OC2M_1		(13)
#define TIMX_CCMR1_OC2M_2		(14)
#define TIMX_CCMR1_OC2CE		(15)


//TIMX_CCMR2 BITS
#define TIMX_CCMR2_CC3S_0		(0)
#define TIMX_CCMR2_CC3S_1		(1)
#define TIMX_CCMR2_IC3PSC_0	(2)
#define TIMX_CCMR2_IC3PSC_1	(3)
#define TIMX_CCMR2_OC3FE	(2)
#define TIMX_CCMR2_OC3PE	(3)
#define TIMX_CCMR2_IC3F_0		(4)
#define TIMX_CCMR2_IC3F_1		(5)
#define TIMX_CCMR2_IC3F_2		(6)
#define TIMX_CCMR2_IC3F_3		(7)
#define TIMX_CCMR2_OC3M_0		(4)
#define TIMX_CCMR2_OC3M_1		(5)
#define TIMX_CCMR2_OC3M_2		(6)
#define TIMX_CCMR2_OC3CE		(7)
#define TIMX_CCMR2_CC4S_0		(8)
#define TIMX_CCMR2_CC4S_1		(9)
#define TIMX_CCMR2_IC4PSC_0	(10)
#define TIMX_CCMR2_IC4PSC_1	(11)
#define TIMX_CCMR2_OC4FE	(10)
#define TIMX_CCMR2_OC4PE	(11)
#define TIMX_CCMR2_IC4F_0		(12)
#define TIMX_CCMR2_IC4F_1		(13)
#define TIMX_CCMR2_IC4F_2		(14)
#define TIMX_CCMR2_IC4F_3		(15)
#define TIMX_CCMR2_OC4M_0		(12)
#define TIMX_CCMR2_OC4M_1		(13)
#define TIMX_CCMR2_OC4M_2		(14)
#define TIMX_CCMR2_OC4CE		(15)


#define TIMX_CCER_CC1E			(0)
#define TIMX_CCER_CC1P			(1)
#define TIMX_CCER_CC2E			(4)
#define TIMX_CCER_CC2P			(5)
#define TIMX_CCER_CC3E			(8)
#define TIMX_CCER_CC3P			(9)
#define TIMX_CCER_CC4E			(12)
#define TIMX_CCER_CC4P			(13)

////TIMX_BDTR BITS
#define TIMX_BDTR_MOE				(15)

/*******************************USART Registers Offset**********************/
#define USART1_BASE_ADDRESS 			(0x40013800)
#define USART2_BASE_ADDRESS 			(0x40004400)
#define USART3_BASE_ADDRESS 			(0x40004800)
#define USARTX_SR_OFFSET					(0X00)
#define USARTX_DR_OFFSET					(0X04)
#define USARTX_BRR_OFFSET					(0X08)
#define USARTX_CR1_OFFSET					(0X0C)
#define USARTX_CR2_OFFSET					(0X10)
#define USARTX_CR3_OFFSET					(0X14)
#define USARTX_GTPR_OFFSET				(0X18)

/*******************************USART Registers Access ****************************/
//USART1
#define USART1_SR_ADDRESS     	HWRG_ADDRESS(USART1_BASE_ADDRESS,USARTX_SR_OFFSET)
#define USART1_SR								HWRG(USART1_SR_ADDRESS)
#define USART1_DR_ADDRESS     	HWRG_ADDRESS(USART1_BASE_ADDRESS,USARTX_DR_OFFSET)
#define USART1_DR								HWRG(USART1_DR_ADDRESS)
#define USART1_BRR_ADDRESS     	HWRG_ADDRESS(USART1_BASE_ADDRESS,USARTX_BRR_OFFSET)
#define USART1_BRR							HWRG(USART1_BRR_ADDRESS)
#define USART1_CR1_ADDRESS     	HWRG_ADDRESS(USART1_BASE_ADDRESS,USARTX_CR1_OFFSET)
#define USART1_CR1							HWRG(USART1_CR1_ADDRESS)
#define USART1_CR2_ADDRESS     	HWRG_ADDRESS(USART1_BASE_ADDRESS,USARTX_CR2_OFFSET)
#define USART1_CR2							HWRG(USART1_CR2_ADDRESS)
#define USART1_CR3_ADDRESS     	HWRG_ADDRESS(USART1_BASE_ADDRESS,USARTX_CR3_OFFSET)
#define USART1_CR3							HWRG(USART1_CR3_ADDRESS)
#define USART1_GTPR_ADDRESS     HWRG_ADDRESS(USART1_BASE_ADDRESS,USARTX_GTPR_OFFSET)
#define USART1_GTPR							HWRG(USART1_GTPR_ADDRESS)


//USART2
#define USART2_SR_ADDRESS     	HWRG_ADDRESS(USART2_BASE_ADDRESS,USARTX_SR_OFFSET)
#define USART2_SR								HWRG(USART2_SR_ADDRESS)
#define USART2_DR_ADDRESS     	HWRG_ADDRESS(USART2_BASE_ADDRESS,USARTX_DR_OFFSET)
#define USART2_DR								HWRG(USART2_DR_ADDRESS)
#define USART2_BRR_ADDRESS     	HWRG_ADDRESS(USART2_BASE_ADDRESS,USARTX_BRR_OFFSET)
#define USART2_BRR							HWRG(USART2_BRR_ADDRESS)
#define USART2_CR1_ADDRESS     	HWRG_ADDRESS(USART2_BASE_ADDRESS,USARTX_CR1_OFFSET)
#define USART2_CR1							HWRG(USART2_CR1_ADDRESS)
#define USART2_CR2_ADDRESS     	HWRG_ADDRESS(USART2_BASE_ADDRESS,USARTX_CR2_OFFSET)
#define USART2_CR2							HWRG(USART2_CR2_ADDRESS)
#define USART2_CR3_ADDRESS     	HWRG_ADDRESS(USART2_BASE_ADDRESS,USARTX_CR3_OFFSET)
#define USART2_CR3							HWRG(USART2_CR3_ADDRESS)
#define USART2_GTPR_ADDRESS     HWRG_ADDRESS(USART2_BASE_ADDRESS,USARTX_GTPR_OFFSET)
#define USART2_GTPR							HWRG(USART2_GTPR_ADDRESS)


//USART3
#define USART3_SR_ADDRESS     	HWRG_ADDRESS(USART3_BASE_ADDRESS,USARTX_SR_OFFSET)
#define USART3_SR								HWRG(USART3_SR_ADDRESS)
#define USART3_DR_ADDRESS     	HWRG_ADDRESS(USART3_BASE_ADDRESS,USARTX_DR_OFFSET)
#define USART3_DR								HWRG(USART3_DR_ADDRESS)
#define USART3_BRR_ADDRESS     	HWRG_ADDRESS(USART3_BASE_ADDRESS,USARTX_BRR_OFFSET)
#define USART3_BRR							HWRG(USART3_BRR_ADDRESS)
#define USART3_CR1_ADDRESS     	HWRG_ADDRESS(USART3_BASE_ADDRESS,USARTX_CR1_OFFSET)
#define USART3_CR1							HWRG(USART3_CR1_ADDRESS)
#define USART3_CR2_ADDRESS     	HWRG_ADDRESS(USART3_BASE_ADDRESS,USARTX_CR2_OFFSET)
#define USART3_CR2							HWRG(USART3_CR2_ADDRESS)
#define USART3_CR3_ADDRESS     	HWRG_ADDRESS(USART3_BASE_ADDRESS,USARTX_CR3_OFFSET)
#define USART3_CR3							HWRG(USART3_CR3_ADDRESS)
#define USART3_GTPR_ADDRESS     HWRG_ADDRESS(USART3_BASE_ADDRESS,USARTX_GTPR_OFFSET)
#define USART3_GTPR							HWRG(USART3_GTPR_ADDRESS)

/*******************************SPI Registers Offset**********************/
#define SPI1_BASE_ADDRESS 			(0x40013000)
#define SPI2_BASE_ADDRESS 			(0x40003800)
#define SPI3_BASE_ADDRESS 			(0x40003C00)
#define SPIX_CR1_OFFSET					(0X00)
#define SPIX_CR2_OFFSET					(0X04)
#define SPIX_SR_OFFSET					(0X08)
#define SPIX_DR_OFFSET					(0X0C)



//SPI1
#define SPI1_CR1_ADDRESS     	HWRG_ADDRESS(SPI1_BASE_ADDRESS,SPIX_CR1_OFFSET)
#define SPI1_CR1							HWRG(SPI1_CR1_ADDRESS)
#define SPI1_CR2_ADDRESS     	HWRG_ADDRESS(SPI1_BASE_ADDRESS,SPIX_CR2_OFFSET)
#define SPI1_CR2							HWRG(SPI1_CR2_ADDRESS)
#define SPI1_SR_ADDRESS     	HWRG_ADDRESS(SPI1_BASE_ADDRESS,SPIX_SR_OFFSET)
#define SPI1_SR								HWRG(SPI1_SR_ADDRESS)
#define SPI1_DR_ADDRESS     	HWRG_ADDRESS(SPI1_BASE_ADDRESS,SPIX_DR_OFFSET)
#define SPI1_DR								HWRG(SPI1_DR_ADDRESS)



//SPI2
#define SPI2_CR1_ADDRESS     	HWRG_ADDRESS(SPI2_BASE_ADDRESS,SPIX_CR1_OFFSET)
#define SPI2_CR1							HWRG(SPI2_CR1_ADDRESS)
#define SPI2_CR2_ADDRESS     	HWRG_ADDRESS(SPI2_BASE_ADDRESS,SPIX_CR2_OFFSET)
#define SPI2_CR2							HWRG(SPI2_CR2_ADDRESS)
#define SPI2_SR_ADDRESS     	HWRG_ADDRESS(SPI2_BASE_ADDRESS,SPIX_SR_OFFSET)
#define SPI2_SR								HWRG(SPI2_SR_ADDRESS)
#define SPI2_DR_ADDRESS     	HWRG_ADDRESS(SPI2_BASE_ADDRESS,SPIX_DR_OFFSET)
#define SPI2_DR								HWRG(SPI2_DR_ADDRESS)



//SPIX_CR1 bits
#define SPIX_CR1_CPHA		(0)
#define SPIX_CR1_CPOL		(1)
#define SPIX_CR1_MSTR		(2)
#define SPIX_CR1_BR0		(3)
#define SPIX_CR1_BR1		(4)
#define SPIX_CR1_BR2		(5)
#define SPIX_CR1_SPE		(6)
#define SPIX_CR1_SSI		(8)
#define SPIX_CR1_SSM		(9)
#define SPIX_CR1_DDF		(11)

//SPIX_SR bits
#define SPIX_SR_RXNE		(0)
#define SPIX_SR_TXE			(1)
#define SPIX_SR_BSY			(7)




/*************************************************ADC******************************************/

/******************************* ADC Registers Base Addresses ******************************/
#define ADC1_BASE_ADDRESS                           (0x40012400)
#define ADC2_BASE_ADDRESS                           (0x40012800)

/******************************* ADC Registers Offsets *************************************/
#define ADC_SR_OFFSET                               (0x00)
#define ADC_CR1_OFFSET                              (0x04)
#define ADC_CR2_OFFSET                              (0x08)
#define ADC_SMPR1_OFFSET                            (0x0C)
#define ADC_SMPR2_OFFSET                            (0x10)
#define ADC_JOFR1_OFFSET                            (0x14)
#define ADC_JOFR2_OFFSET                            (0x18)
#define ADC_JOFR3_OFFSET                            (0x1C)
#define ADC_JOFR4_OFFSET                            (0x20)
#define ADC_HTR_OFFSET                              (0x24)
#define ADC_LTR_OFFSET                              (0x28)
#define ADC_SQR1_OFFSET                             (0x2C)
#define ADC_SQR2_OFFSET                             (0x30)
#define ADC_SQR3_OFFSET                             (0x34)
#define ADC_JSQR_OFFSET                             (0x38)
#define ADC_JDR1_OFFSET                             (0x3C)
#define ADC_JDR2_OFFSET                             (0x40)
#define ADC_JDR3_OFFSET                             (0x44)
#define ADC_JDR4_OFFSET                             (0x48)
#define ADC_DR_OFFSET                               (0x4C)

/******************************* ADC Registers Addresses ***********************************/
#define ADC1_SR_ADDRESS                             HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_SR_OFFSET)
#define ADC1_CR1_ADDRESS                            HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_CR1_OFFSET)
#define ADC1_CR2_ADDRESS                            HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_CR2_OFFSET)
#define ADC1_SMPR1_ADDRESS                          HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_SMPR1_OFFSET)
#define ADC1_SMPR2_ADDRESS                          HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_SMPR2_OFFSET)
#define ADC1_JOFR1_ADDRESS                          HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_JOFR1_OFFSET)
#define ADC1_JOFR2_ADDRESS                          HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_JOFR2_OFFSET)
#define ADC1_JOFR3_ADDRESS                          HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_JOFR3_OFFSET)
#define ADC1_JOFR4_ADDRESS                          HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_JOFR4_OFFSET)
#define ADC1_HTR_ADDRESS                            HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_HTR_OFFSET)
#define ADC1_LTR_ADDRESS                            HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_LTR_OFFSET)
#define ADC1_SQR1_ADDRESS                           HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_SQR1_OFFSET)
#define ADC1_SQR2_ADDRESS                           HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_SQR2_OFFSET)
#define ADC1_SQR3_ADDRESS                           HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_SQR3_OFFSET)
#define ADC1_JSQR_ADDRESS                           HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_JSQR_OFFSET)
#define ADC1_JDR1_ADDRESS                           HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_JDR1_OFFSET)
#define ADC1_JDR2_ADDRESS                           HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_JDR2_OFFSET)
#define ADC1_JDR3_ADDRESS                           HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_JDR3_OFFSET)
#define ADC1_JDR4_ADDRESS                           HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_JDR4_OFFSET)
#define ADC1_DR_ADDRESS                             HWRG_ADDRESS(ADC1_BASE_ADDRESS, ADC_DR_OFFSET)

#define ADC2_SR_ADDRESS                             HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_SR_OFFSET)
#define ADC2_CR1_ADDRESS                            HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_CR1_OFFSET)
#define ADC2_CR2_ADDRESS                            HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_CR2_OFFSET)
#define ADC2_SMPR1_ADDRESS                          HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_SMPR1_OFFSET)
#define ADC2_SMPR2_ADDRESS                          HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_SMPR2_OFFSET)
#define ADC2_JOFR1_ADDRESS                          HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_JOFR1_OFFSET)
#define ADC2_JOFR2_ADDRESS                          HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_JOFR2_OFFSET)
#define ADC2_JOFR3_ADDRESS                          HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_JOFR3_OFFSET)
#define ADC2_JOFR4_ADDRESS                          HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_JOFR4_OFFSET)
#define ADC2_HTR_ADDRESS                            HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_HTR_OFFSET)
#define ADC2_LTR_ADDRESS                            HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_LTR_OFFSET)
#define ADC2_SQR1_ADDRESS                           HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_SQR1_OFFSET)
#define ADC2_SQR2_ADDRESS                           HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_SQR2_OFFSET)
#define ADC2_SQR3_ADDRESS                           HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_SQR3_OFFSET)
#define ADC2_JSQR_ADDRESS                           HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_JSQR_OFFSET)
#define ADC2_JDR1_ADDRESS                           HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_JDR1_OFFSET)
#define ADC2_JDR2_ADDRESS                           HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_JDR2_OFFSET)
#define ADC2_JDR3_ADDRESS                           HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_JDR3_OFFSET)
#define ADC2_JDR4_ADDRESS                           HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_JDR4_OFFSET)
#define ADC2_DR_ADDRESS                             HWRG_ADDRESS(ADC2_BASE_ADDRESS, ADC_DR_OFFSET)

/******************************* ADC Registers Access ***************************************/
#define ADC1_SR                                     HWRG(ADC1_SR_ADDRESS)
#define ADC1_CR1                                    HWRG(ADC1_CR1_ADDRESS)
#define ADC1_CR2                                    HWRG(ADC1_CR2_ADDRESS)
#define ADC1_SMPR1                                  HWRG(ADC1_SMPR1_ADDRESS)
#define ADC1_SMPR2                                  HWRG(ADC1_SMPR2_ADDRESS)
#define ADC1_JOFR1                                  HWRG(ADC1_JOFR1_ADDRESS)
#define ADC1_JOFR2                                  HWRG(ADC1_JOFR2_ADDRESS)
#define ADC1_JOFR3                                  HWRG(ADC1_JOFR3_ADDRESS)
#define ADC1_JOFR4                                  HWRG(ADC1_JOFR4_ADDRESS)
#define ADC1_HTR                                    HWRG(ADC1_HTR_ADDRESS)
#define ADC1_LTR                                    HWRG(ADC1_LTR_ADDRESS)
#define ADC1_SQR1                                   HWRG(ADC1_SQR1_ADDRESS)
#define ADC1_SQR2                                   HWRG(ADC1_SQR2_ADDRESS)
#define ADC1_SQR3                                   HWRG(ADC1_SQR3_ADDRESS)
#define ADC1_JSQR                                   HWRG(ADC1_JSQR_ADDRESS)
#define ADC1_JDR1                                   HWRG(ADC1_JDR1_ADDRESS)
#define ADC1_JDR2                                   HWRG(ADC1_JDR2_ADDRESS)
#define ADC1_JDR3                                   HWRG(ADC1_JDR3_ADDRESS)
#define ADC1_JDR4                                   HWRG(ADC1_JDR4_ADDRESS)
#define ADC1_DR                                     HWRG(ADC1_DR_ADDRESS)

#define ADC2_SR                                     HWRG(ADC2_SR_ADDRESS)
#define ADC2_CR1                                    HWRG(ADC2_CR1_ADDRESS)
#define ADC2_CR2                                    HWRG(ADC2_CR2_ADDRESS)
#define ADC2_SMPR1                                  HWRG(ADC2_SMPR1_ADDRESS)
#define ADC2_SMPR2                                  HWRG(ADC2_SMPR2_ADDRESS)
#define ADC2_JOFR1                                  HWRG(ADC2_JOFR1_ADDRESS)
#define ADC2_JOFR2                                  HWRG(ADC2_JOFR2_ADDRESS)
#define ADC2_JOFR3                                  HWRG(ADC2_JOFR3_ADDRESS)
#define ADC2_JOFR4                                  HWRG(ADC2_JOFR4_ADDRESS)
#define ADC2_HTR                                    HWRG(ADC2_HTR_ADDRESS)
#define ADC2_LTR                                    HWRG(ADC2_LTR_ADDRESS)
#define ADC2_SQR1                                   HWRG(ADC2_SQR1_ADDRESS)
#define ADC2_SQR2                                   HWRG(ADC2_SQR2_ADDRESS)
#define ADC2_SQR3                                   HWRG(ADC2_SQR3_ADDRESS)
#define ADC2_JSQR                                   HWRG(ADC2_JSQR_ADDRESS)
#define ADC2_JDR1                                   HWRG(ADC2_JDR1_ADDRESS)
#define ADC2_JDR2                                   HWRG(ADC2_JDR2_ADDRESS)
#define ADC2_JDR3                                   HWRG(ADC2_JDR3_ADDRESS)
#define ADC2_JDR4                                   HWRG(ADC2_JDR4_ADDRESS)
#define ADC2_DR                                     HWRG(ADC2_DR_ADDRESS)

/******************************* ADC_SR BIT FIELD **************************************/
#define ADC_SR_AWD                                  (0)
#define ADC_SR_EOC                                  (1)
#define ADC_SR_JEOC                                 (2)
#define ADC_SR_JSTRT                                (3)
#define ADC_SR_STRT                                 (4)

/******************************* ADC_CR1 BIT FIELD **************************************/
#define ADC_CR1_AWDCH                               (0)
#define ADC_CR1_EOCIE                               (5)
#define ADC_CR1_AWDIE                               (6)
#define ADC_CR1_JEOCIE                              (7)
#define ADC_CR1_SCAN                                (8)
#define ADC_CR1_AWDSGL                              (9)
#define ADC_CR1_JAUTO                               (10)
#define ADC_CR1_DISCEN                              (11)
#define ADC_CR1_JDISCEN                             (12)
#define ADC_CR1_DISCNUM                             (13)
#define ADC_CR1_DUALMOD                             (16)
#define ADC_CR1_JAWDEN                              (22)
#define ADC_CR1_AWDEN                               (23)

/******************************* ADC_CR2 BIT FIELD **************************************/
#define ADC_CR2_ADON                                (0)
#define ADC_CR2_CONT                                (1)
#define ADC_CR2_CAL                                 (2)
#define ADC_CR2_RSTCAL                              (3)
#define ADC_CR2_DMA                                 (8)
#define ADC_CR2_ALIGN                               (11)
#define ADC_CR2_JEXTSEL                             (12)
#define ADC_CR2_JEXTTRIG                            (15)
#define ADC_CR2_EXTSEL                              (17)
#define ADC_CR2_EXTTRIG                             (20)
#define ADC_CR2_JSWSTART                            (21)
#define ADC_CR2_SWSTART                             (22)
#define ADC_CR2_TSVREFE                             (23)

/******************************* ADC_SMPR1 BIT FIELD **************************************/
#define ADC_SMPR1_SMP10                             (0)
#define ADC_SMPR1_SMP11                             (3)
#define ADC_SMPR1_SMP12                             (6)
#define ADC_SMPR1_SMP13                             (9)
#define ADC_SMPR1_SMP14                             (12)
#define ADC_SMPR1_SMP15                             (15)
#define ADC_SMPR1_SMP16                             (18)
#define ADC_SMPR1_SMP17                             (21)

/******************************* ADC_SMPR2 BIT FIELD **************************************/
#define ADC_SMPR2_SMP0                              (0)
#define ADC_SMPR2_SMP1                              (3)
#define ADC_SMPR2_SMP2                              (6)
#define ADC_SMPR2_SMP3                              (9)
#define ADC_SMPR2_SMP4                              (12)
#define ADC_SMPR2_SMP5                              (15)
#define ADC_SMPR2_SMP6                              (18)
#define ADC_SMPR2_SMP7                              (21)
#define ADC_SMPR2_SMP8                              (24)
#define ADC_SMPR2_SMP9                              (27)

/******************************* ADC_SQR1 BIT FIELD **************************************/
#define ADC_SQR1_SQ13                               (0)
#define ADC_SQR1_SQ14                               (5)
#define ADC_SQR1_SQ15                               (10)
#define ADC_SQR1_SQ16                               (15)
#define ADC_SQR1_L                                  (20)

/******************************* ADC_SQR2 BIT FIELD **************************************/
#define ADC_SQR2_SQ7                                (0)
#define ADC_SQR2_SQ8                                (5)
#define ADC_SQR2_SQ9                                (10)
#define ADC_SQR2_SQ10                               (15)
#define ADC_SQR2_SQ11                               (20)
#define ADC_SQR2_SQ12                               (25)

/******************************* ADC_SQR3 BIT FIELD **************************************/
#define ADC_SQR3_SQ1                                (0)
#define ADC_SQR3_SQ2                                (5)
#define ADC_SQR3_SQ3                                (10)
#define ADC_SQR3_SQ4                                (15)
#define ADC_SQR3_SQ5                                (20)
#define ADC_SQR3_SQ6                                (25)

/******************************* ADC_JSQR BIT FIELD **************************************/
#define ADC_JSQR_JSQ1                               (0)
#define ADC_JSQR_JSQ2                               (5)
#define ADC_JSQR_JSQ3                               (10)
#define ADC_JSQR_JSQ4                               (15)
#define ADC_JSQR_JL                                 (20)





#endif







