/**
@file: MCAL_EXTERNAL_INTERRUPTS.h
@author: M4_TEAM 
@creation_date: date
*/

#ifndef MCAL_EXTERNAL_INTERRUPTS_H
#define MCAL_EXTERNAL_INTERRUPTS_H

/*******************INCLUDES SECTION START************************/
#include "../GPIO/MCAL_GPIO.h"
#include "MCAL_NVIC.h"
/*******************INCLUDES SECTION END  ************************/




/*******************MACROS DEFINITION SECTION START***************/


/*******************MACROS DEFINITION SECTION END  ***************/




/*******************MACROS LIKE FUNCTIONS SECTION START***********
//ENABLE INTERRUPT ON EXTERNAL LINE
#define EXTI0_ENABLE()			(SET_BIT_K(EXTI_IMR,MR0))
#define EXTI1_ENABLE()			(SET_BIT_K(EXTI_IMR,MR1))
#define EXTI2_ENABLE()			(SET_BIT_K(EXTI_IMR,MR2))
#define EXTI3_ENABLE()			(SET_BIT_K(EXTI_IMR,MR3))
#define EXTI4_ENABLE()			(SET_BIT_K(EXTI_IMR,MR4))
#define EXTI5_ENABLE()			(SET_BIT_K(EXTI_IMR,MR5))
#define EXTI6_ENABLE()			(SET_BIT_K(EXTI_IMR,MR6))
#define EXTI7_ENABLE()			(SET_BIT_K(EXTI_IMR,MR7))
#define EXTI8_ENABLE()			(SET_BIT_K(EXTI_IMR,MR8))
#define EXTI9_ENABLE()			(SET_BIT_K(EXTI_IMR,MR9))
#define EXTI10_ENABLE()			(SET_BIT_K(EXTI_IMR,MR10))
#define EXTI11_ENABLE()			(SET_BIT_K(EXTI_IMR,MR11))
#define EXTI12_ENABLE()			(SET_BIT_K(EXTI_IMR,MR12))
#define EXTI13_ENABLE()			(SET_BIT_K(EXTI_IMR,MR13))
#define EXTI14_ENABLE()			(SET_BIT_K(EXTI_IMR,MR14))
#define EXTI15_ENABLE()			(SET_BIT_K(EXTI_IMR,MR15))

//DISABLE INTERRUPT ON EXTERNAL LINE
#define EXTI0_DISABLE()			(CLEAR_BIT_K(EXTI_IMR,MR0))
#define EXTI1_DISABLE()			(CLEAR_BIT_K(EXTI_IMR,MR1))
#define EXTI2_DISABLE()			(CLEAR_BIT_K(EXTI_IMR,MR2))
#define EXTI3_DISABLE()			(CLEAR_BIT_K(EXTI_IMR,MR3))
#define EXTI4_DISABLE()			(CLEAR_BIT_K(EXTI_IMR,MR4))
#define EXTI5_DISABLE()			(CLEAR_BIT_K(EXTI_IMR,MR5))
#define EXTI6_DISABLE()			(CLEAR_BIT_K(EXTI_IMR,MR6))
#define EXTI7_DISABLE()			(CLEAR_BIT_K(EXTI_IMR,MR7))
#define EXTI8_DISABLE()			(CLEAR_BIT_K(EXTI_IMR,MR8))
#define EXTI9_DISABLE()			(CLEAR_BIT_K(EXTI_IMR,MR9))
#define EXTI10_DISABLE()		(CLEAR_BIT_K(EXTI_IMR,MR10))
#define EXTI11_DISABLE()		(CLEAR_BIT_K(EXTI_IMR,MR11))
#define EXTI12_DISABLE()		(CLEAR_BIT_K(EXTI_IMR,MR12))
#define EXTI13_DISABLE()		(CLEAR_BIT_K(EXTI_IMR,MR13))
#define EXTI14_DISABLE()		(CLEAR_BIT_K(EXTI_IMR,MR14))
#define EXTI15_DISABLE()		(CLEAR_BIT_K(EXTI_IMR,MR15))

//SET INTERRUPT ON EXTERNAL LINE ON RISING EDGE
#define EXTI0_SET_RISING_EDGE()			(SET_BIT_K(EXTI_RTSR,TR0))
#define EXTI1_SET_RISING_EDGE()			(SET_BIT_K(EXTI_RTSR,TR1))
#define EXTI2_SET_RISING_EDGE()			(SET_BIT_K(EXTI_RTSR,TR2))
#define EXTI3_SET_RISING_EDGE()			(SET_BIT_K(EXTI_RTSR,TR3))
#define EXTI4_SET_RISING_EDGE()			(SET_BIT_K(EXTI_RTSR,TR4))
#define EXTI5_SET_RISING_EDGE()			(SET_BIT_K(EXTI_RTSR,TR5))
#define EXTI6_SET_RISING_EDGE()			(SET_BIT_K(EXTI_RTSR,TR6))
#define EXTI7_SET_RISING_EDGE()			(SET_BIT_K(EXTI_RTSR,TR7))
#define EXTI8_SET_RISING_EDGE()			(SET_BIT_K(EXTI_RTSR,TR8))
#define EXTI9_SET_RISING_EDGE()			(SET_BIT_K(EXTI_RTSR,TR9))
#define EXTI10_SET_RISING_EDGE()		(SET_BIT_K(EXTI_RTSR,TR10))
#define EXTI11_SET_RISING_EDGE()		(SET_BIT_K(EXTI_RTSR,TR11))
#define EXTI12_SET_RISING_EDGE()		(SET_BIT_K(EXTI_RTSR,TR12))
#define EXTI13_SET_RISING_EDGE()		(SET_BIT_K(EXTI_RTSR,TR13))
#define EXTI14_SET_RISING_EDGE()		(SET_BIT_K(EXTI_RTSR,TR14))
#define EXTI15_SET_RISING_EDGE()		(SET_BIT_K(EXTI_RTSR,TR15))

//SET INTERRUPT ON EXTERNAL LINE ON FALLING EDGE
#define EXTI0_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR0))
#define EXTI1_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR1))
#define EXTI2_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR2))
#define EXTI3_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR3))
#define EXTI4_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR4))
#define EXTI5_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR5))
#define EXTI6_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR6))
#define EXTI7_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR7))
#define EXTI8_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR8))
#define EXTI9_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR9))
#define EXTI10_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR10))
#define EXTI11_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR11))
#define EXTI12_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR12))
#define EXTI13_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR13))
#define EXTI14_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR14))
#define EXTI15_SET_FALLING_EDGE()			(SET_BIT_K(EXTI_FTSR,TR15))

//CLEAR FLAG
#define EXTI0_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR0))
#define EXTI1_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR1))
#define EXTI2_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR2))
#define EXTI3_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR3))
#define EXTI4_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR4))
#define EXTI5_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR5))
#define EXTI6_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR6))
#define EXTI7_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR7))
#define EXTI8_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR8))
#define EXTI9_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR9))
#define EXTI10_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR10))
#define EXTI11_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR11))
#define EXTI12_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR12))
#define EXTI13_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR13))
#define EXTI14_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR14))
#define EXTI15_CLEAR_FLAG()						(SET_BIT_K(EXTI_PR,PR15))

#define EXTI0_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR0))
#define EXTI1_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR1))
#define EXTI2_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR2))
#define EXTI3_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR3))
#define EXTI4_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR4))
#define EXTI5_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR5))
#define EXTI6_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR6))
#define EXTI7_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR7))
#define EXTI8_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR8))
#define EXTI9_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR9))
#define EXTI10_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR10))
#define EXTI11_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR11))
#define EXTI12_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR12))
#define EXTI13_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR13))
#define EXTI14_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR14))
#define EXTI15_READ_FLAG()						(READ_BIT_K(EXTI_PR,PR15))

//select interrupt pin port
#define EXTI0_PORTA_SELECT()					(AFIO_EXTICR1&=0XFFF0)
#define EXTI0_PORTB_SELECT()					({\
    AFIO_EXTICR1&=0XFFF0;\
    AFIO_EXTICR1|=0X0001;\
})
#define EXTI0_PORTC_SELECT()					({\
    AFIO_EXTICR1&=0XFFF0;\
    AFIO_EXTICR1|=0x2;\
})

#define EXTI1_PORTA_SELECT()					(AFIO_EXTICR1&=0XFF0F)
#define EXTI1_PORTB_SELECT()					({\
    AFIO_EXTICR1&=0XFF0F;\
    AFIO_EXTICR1|=0x10;\
})
#define EXTI1_PORTC_SELECT()					({\
    AFIO_EXTICR1&=0XFF0F;\
    AFIO_EXTICR1|=0x20;\
})

#define EXTI2_PORTA_SELECT()					(AFIO_EXTICR1&=0XF0FF)
#define EXTI2_PORTB_SELECT()					({\
    AFIO_EXTICR1&=0XF0FF;\
    AFIO_EXTICR1|=0x100;\
})
#define EXTI2_PORTC_SELECT()					({\
    AFIO_EXTICR1&=0XF0FF;\
    AFIO_EXTICR1|=0x200;\
})

#define EXTI3_PORTA_SELECT()					(AFIO_EXTICR1&=0X0FFF)
#define EXTI3_PORTB_SELECT()					({\
    AFIO_EXTICR1&=0X0FFF;\
    AFIO_EXTICR1|=0x1000;\
})
#define EXTI3_PORTC_SELECT()					({\
    AFIO_EXTICR1&=0X0FFF;\
    AFIO_EXTICR1|=0x2000;\
})

#define EXTI4_PORTA_SELECT()					(AFIO_EXTICR1&=0XFFF0)
#define EXTI4_PORTB_SELECT()					({\
    AFIO_EXTICR2&=0XFFF0;\
    AFIO_EXTICR2|=0x1;\
})
#define EXTI4_PORTC_SELECT()					({\
    AFIO_EXTICR2&=0XFFF0;\
    AFIO_EXTICR2|=0x2;\
})

#define EXTI5_PORTA_SELECT()					(AFIO_EXTICR1&=0XFF0F)
#define EXTI5_PORTB_SELECT()					({\
    AFIO_EXTICR2&=0XFF0F;\
    AFIO_EXTICR2|=0x10;\
})
#define EXTI5_PORTC_SELECT()					({\
    AFIO_EXTICR2&=0XFF0F;\
    AFIO_EXTICR2|=0x20;\
})

#define EXTI6_PORTA_SELECT()					(AFIO_EXTICR1&=0XF0FF)
#define EXTI6_PORTB_SELECT()					({\
    AFIO_EXTICR2&=0XF0FF;\
    AFIO_EXTICR2|=0x100;\
})
#define EXTI6_PORTC_SELECT()					({\
    AFIO_EXTICR2&=0XF0FF;\
    AFIO_EXTICR2|=0x200;\
})

#define EXTI7_PORTA_SELECT()					(AFIO_EXTICR1&=0X0FFF)
#define EXTI7_PORTB_SELECT()					({\
    AFIO_EXTICR2&=0X0FFF;\
    AFIO_EXTICR2|=0x1000;\
})
#define EXTI7_PORTC_SELECT()					({\
    AFIO_EXTICR2&=0X0FFF;\
    AFIO_EXTICR2|=0x2000;\
})

#define EXTI8_PORTA_SELECT()					(AFIO_EXTICR1&=0XFFF0)
#define EXTI8_PORTB_SELECT()					({\
    AFIO_EXTICR3&=0XFFF0;\
    AFIO_EXTICR3|=0x1;\
})
#define EXTI8_PORTC_SELECT()					({\
    AFIO_EXTICR3&=0XFFF0;\
    AFIO_EXTICR3|=0x2;\
})

#define EXTI9_PORTA_SELECT()					(AFIO_EXTICR1&=0XFF0F)
#define EXTI9_PORTB_SELECT()					({\
    AFIO_EXTICR3&=0XFF0F;\
    AFIO_EXTICR3|=0x10;\
})
#define EXTI9_PORTC_SELECT()					({\
    AFIO_EXTICR3&=0XFF0F;\
    AFIO_EXTICR3|=0x20;\
})

#define EXTI10_PORTA_SELECT()					(AFIO_EXTICR1&=0XF0FF)
#define EXTI10_PORTB_SELECT()					({\
    AFIO_EXTICR3&=0XF0FF;\
    AFIO_EXTICR3|=0x100;\
})
#define EXTI10_PORTC_SELECT()					({\
    AFIO_EXTICR3&=0XF0FF;\
    AFIO_EXTICR3|=0x200;\
})

#define EXTI11_PORTA_SELECT()					(AFIO_EXTICR1&=0X0FFF)
#define EXTI11_PORTB_SELECT()					({\
    AFIO_EXTICR3&=0X0FFF;\
    AFIO_EXTICR3|=0x1000;\
})
#define EXTI11_PORTC_SELECT()					({\
    AFIO_EXTICR3&=0X0FFF;\
    AFIO_EXTICR3|=0x2000;\
})

#define EXTI12_PORTA_SELECT()					(AFIO_EXTICR1&=0XFFF0)
#define EXTI12_PORTB_SELECT()					({\
    AFIO_EXTICR4&=0XFFF0;\
    AFIO_EXTICR4|=0x1;\
})
#define EXTI12_PORTC_SELECT()					({\
    AFIO_EXTICR4&=0XFFF0;\
    AFIO_EXTICR4|=0x2;\
})

#define EXTI13_PORTA_SELECT()					(AFIO_EXTICR1&=0XFF0F)
#define EXTI13_PORTB_SELECT()					({\
    AFIO_EXTICR4&=0XFF0F;\
    AFIO_EXTICR4|=0x10;\
})
#define EXTI13_PORTC_SELECT()					({\
    AFIO_EXTICR4&=0XFF0F;\
    AFIO_EXTICR4|=0x20;\
})

#define EXTI14_PORTA_SELECT()					(AFIO_EXTICR1&=0XF0FF)
#define EXTI14_PORTB_SELECT()					({\
    AFIO_EXTICR4&=0XF0FF;\
    AFIO_EXTICR4|=0x100;\
})
#define EXTI14_PORTC_SELECT()					({\
    AFIO_EXTICR4&=0XF0FF;\
    AFIO_EXTICR4|=0x200;\
})

#define EXTI15_PORTA_SELECT()					(AFIO_EXTICR1&=0X0FFF)
#define EXTI15_PORTB_SELECT()					({\
    AFIO_EXTICR4&=0X0FFF;\
    AFIO_EXTICR4|=0x1000;\
})
#define EXTI15_PORTC_SELECT()					({\
    AFIO_EXTICR4&=0X0FFF;\
    AFIO_EXTICR4|=0x2000;\
})
/*******************MACROS LIKE FUNCTIONS SECTION END  ***********/




/*******************DATA TYPES DECLARATION SECTION START**********

typedef enum{
	RISING_EDGE,
	FALLING_EDGE
}Exti_mode_t;

typedef struct{
	Pin_Config_t gpio_pin;
	Exti_mode_t mode;
	void (*InterruptHandler)(void);
}Exti_Config_t;
/*******************DATA TYPES DECLARATION SECTION END  **********/




/*******************FUCNCTIONS PROTOTYPES (APIS) SECTION START****
Std_ReturnType_t EXTI_init(Exti_Config_t *Exti_ptr);
Std_ReturnType_t EXTI_deinit(Exti_Config_t *Exti_ptr);
/*******************FUCNCTIONS PROTOTYPES (APIS) SECTION END  ****/




#endif

