



#include "MCAL_INTERNAL_INTERRUPTS.h"


//Timer 1 Interrupts    
void TIMER1_UPDATE_INTERRUPT_ENABLE(void){
	SET_BIT(TIM1->DIER,TIM_DIER_UIE);
}
void TIMER1_CC1_INTERRUPT_ENABLE(void){
	SET_BIT(TIM1->DIER,TIM_DIER_CC1IE);
}
void TIMER1_CC2_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM1->DIER,TIM_DIER_CC2IE));
}
void TIMER1_CC3_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM1->DIER,TIM_DIER_CC3IE));
}
void TIMER1_CC4_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM1->DIER,TIM_DIER_CC4IE));
}

void TIMER1_UPDATE_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM1->DIER,TIM_DIER_UIE));
}
void TIMER1_CC1_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM1->DIER,TIM_DIER_CC1IE));
}
void TIMER1_CC2_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM1->DIER,TIM_DIER_CC2IE));
}
void TIMER1_CC3_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM1->DIER,TIM_DIER_CC3IE));
}
void TIMER1_CC4_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM1->DIER,TIM_DIER_CC4IE));
}

void TIMER1_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM1->SR,TIM_SR_UIF));
}
void TIMER1_CCP1_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM1->SR,TIM_SR_CC1IF));
}
void TIMER1_CCP2_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM1->SR,TIM_SR_CC2IF));
}
void TIMER1_CCP3_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM1->SR,TIM_SR_CC3IF));
}
void TIMER1_CCP4_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM1->SR,TIM_SR_CC4IF));
}

//Timer 2 Interrupts    
void TIMER2_UPDATE_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM2->DIER,TIM_DIER_UIE));
}
void TIMER2_CC1_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM2->DIER,TIM_DIER_CC1IE));
}
void TIMER2_CC2_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM2->DIER,TIM_DIER_CC2IE));
}
void TIMER2_CC3_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM2->DIER,TIM_DIER_CC3IE));
}
void TIMER2_CC4_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM2->DIER,TIM_DIER_CC4IE));
}

void TIMER2_UPDATE_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM2->DIER,TIM_DIER_UIE));
}
void TIMER2_CC1_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM2->DIER,TIM_DIER_CC1IE));
}
void TIMER2_CC2_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM2->DIER,TIM_DIER_CC2IE));
}
void TIMER2_CC3_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM2->DIER,TIM_DIER_CC3IE));
}
void TIMER2_CC4_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM2->DIER,TIM_DIER_CC4IE));
}

void TIMER2_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM2->SR,TIM_SR_UIF));
}
void TIMER2_CCP1_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM2->SR,TIM_SR_CC1IF));
}
void TIMER2_CCP2_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM2->SR,TIM_SR_CC2IF));
}
void TIMER2_CCP3_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM2->SR,TIM_SR_CC3IF));
}
void TIMER2_CCP4_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM2->SR,TIM_SR_CC4IF));
}

//Timer 3 Interrupts      
void TIMER3_UPDATE_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM3->DIER,TIM_DIER_UIE));
}
void TIMER3_CC1_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM3->DIER,TIM_DIER_CC1IE));
}
void TIMER3_CC2_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM3->DIER,TIM_DIER_CC2IE));
}
void TIMER3_CC3_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM3->DIER,TIM_DIER_CC3IE));
}
void TIMER3_CC4_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM3->DIER,TIM_DIER_CC4IE));
}

void TIMER3_UPDATE_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM3->DIER,TIM_DIER_UIE));
}
void TIMER3_CC1_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM3->DIER,TIM_DIER_CC1IE));
}
void TIMER3_CC2_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM3->DIER,TIM_DIER_CC2IE));
}
void TIMER3_CC3_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM3->DIER,TIM_DIER_CC3IE));
}

void TIMER3_CC4_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM3->DIER,TIM_DIER_CC4IE));
}

void TIMER3_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM3->SR,TIM_SR_UIF));
}
void TIMER3_CCP1_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM3->SR,TIM_SR_CC1IF));
}
void TIMER3_CCP2_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM3->SR,TIM_SR_CC2IF));
}
void TIMER3_CCP3_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM3->SR,TIM_SR_CC3IF));
}
void TIMER3_CCP4_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM3->SR,TIM_SR_CC4IF));
}
//Timer 4 Interrupts    
void TIMER4_UPDATE_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM4->DIER,TIM_DIER_UIE));
}
void TIMER4_CC1_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM4->DIER,TIM_DIER_CC1IE));
}
void TIMER4_CC2_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM4->DIER,TIM_DIER_CC2IE));
}
void TIMER4_CC3_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM4->DIER,TIM_DIER_CC3IE));
}
void TIMER4_CC4_INTERRUPT_ENABLE(void){
	(SET_BIT(TIM4->DIER,TIM_DIER_CC4IE));
}

void TIMER4_UPDATE_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM4->DIER,TIM_DIER_UIE));
}
void TIMER4_CC1_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM4->DIER,TIM_DIER_CC1IE));
}
void TIMER4_CC2_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM4->DIER,TIM_DIER_CC2IE));
}
void TIMER4_CC3_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM4->DIER,TIM_DIER_CC3IE));
}
void TIMER4_CC4_INTERRUPT_DISABLE(void){
	(CLEAR_BIT(TIM4->DIER,TIM_DIER_CC4IE));
}

void TIMER4_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM4->SR,TIM_SR_UIF));
}
void TIMER4_CCP1_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM4->SR,TIM_SR_CC1IF));
}
void TIMER4_CCP2_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM4->SR,TIM_SR_CC2IF));
}
void TIMER4_CCP3_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM4->SR,TIM_SR_CC3IF));
}
void TIMER4_CCP4_CLEAR_FLAG(void){
	(CLEAR_BIT(TIM4->SR,TIM_SR_CC4IF));
}
